### ISSUE TITLE
[Flickr][Mongo] Use correct attribute type

### ISSUE THREAD

**Issue by jooservices** [jooservices/XGallery#48]
<img width="1792" alt="Screen Shot 2020-06-22 at 05 51 07" src="https://user-images.githubusercontent.com/2688707/85236915-7fa11a00-b44c-11ea-90fd-c822984a9b7e.png">

- **family**
- **friend**
actually should be bool ( or int ). These are not string.
And **description** if empty we should not insert into database

**Comment by thongphp** [comment]
Actually, this is map from API response. I think there are some reason that the Provider provide data like this.

_And description if empty we should not insert into database_
--> This is dynamic object from API response, in general I think we just keep all data information cause we store in MongoDB. At least we can have an wrap function before insert to remove empty "property". What do you think?

**Comment by jooservices** [comment]
For friend & family i believe it's flag ( Boolean  ) to determine if that NSID is ur friend or family. So please optimize it.

**Comment by jooservices** [comment]
Anyways this issue should be lowest priority

**Comment by jooservices** [comment]
For sample 
We have "empty" description field. In performance story. It's mean wasted of data.
